## Imports

In [1]:
import numpy as np, pandas as pd, sqlalchemy, sqlite3  
pd.set_option('display.max_columns', None)

## Load Database

In [2]:
conn = sqlite3.connect('../..//Ballbase.db') 
cur = conn.cursor() 
cur.execute('SELECT * FROM sqlite_master WHERE type="table";')
tables=cur.fetchall()
print(tables)  
conn.close()

[('table', 'Season_Stats_2022-23', 'Season_Stats_2022-23', 24, 'CREATE TABLE "Season_Stats_2022-23" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"PLAYER_AGE" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'Season_Stats_1994-95', 'Season_Stats_1994-95', 45, 'CREATE TABLE "Season_Stats_1994-95" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"PLAYER_AGE" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'Season_Stats_2023-24', 'Season_Stats_2023-24', 2, 'CREATE TABLE "Season_Stats_2023-24" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"Age" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'sqlite:///../../Ballbase.db', 'sqlite:///../../Ballbase.db', 55, 'CREATE TABLE "sqlite:///../../Ballbase.db" (\n\t"index" BIGINT, \n\t"Player" TEXT, \n\t"Pos" TEXT, \n\t"Age" BIGINT, \n\t"Tm" TEXT, \n\t"G" BIGINT, \n\t"GS" BIGINT, \n\t"MP" BIGINT, \n\t"FG" FLOAT, \n\t"FGA" FLOAT, \n\t"FG%" FLOAT, \n\t"3P" FLOAT, \n\t"3PA" FLOAT, \n\t"3P%" FLOAT, \n\t"2P" FLOAT, \n\t"2PA" FLOAT, \n\t"2P%" FLOAT, \n\t"FT" FLOAT, \n\t"FTA" FLOAT, \n\t"FT%" FLOAT, \n\t"ORB" FLOAT, \n\t"DRB" FLOAT, \n\t"TRB" FLOAT, \n\t"AST" FLOAT, \n\t"STL" FLOAT, \n\t"BLK" FLOAT, \n\t"TOV" FLOAT, \n\t"PF" FLOAT, \n\t"PTS" FLOAT, \n\t"ORtg" BIGINT, \n\t"DRtg" BIGINT\n)'), ('table', 'Advanced_2023-24', 'Advanced_2023-24', 62, 'CREATE TABLE "Advanced_2023-24" (\n\t"Player" TEXT, \n\t"Pos" TEXT, \n\t"Age" BIGINT, \n\t"Tm" TEXT, \n\t"G" BIGINT, \n\t"MP" BIGINT, \n\t"PER" FLOAT, \n\t"TS%" FLOAT, \n\t"3PAr" FLOAT, \n\t"FTr" FLOAT, \n\t"ORB%" FLOAT, \n\t"DRB%" FLOAT, \n\t"TRB%" FLOAT, \n\t"AST%" FLOAT, \n\t"STL%" FLOAT, \n\t"BLK%" FLOAT, \n\t"TOV%" FLOAT, \n\t"USG%" FLOAT, \n\t"OWS" FLOAT, \n\t"DWS" FLOAT, \n\t"WS" FLOAT, \n\t"WS/48" FLOAT, \n\t"OBPM" FLOAT, \n\t"DBPM" FLOAT, \n\t"BPM" FLOAT, \n\t"VORP" FLOAT\n)'), ('table', 'Averages_2023-24', 'Averages_2023-24', 153, 'CREATE TABLE "Averages_2023-24" (\n\t"Player" TEXT, \n\t"Pos" TEXT, \n\t"Age" BIGINT, \n\t"Tm" TEXT, \n\t"G" BIGINT, \n\t"GS" BIGINT, \n\t"MP" FLOAT, \n\t"FG" FLOAT, \n\t"FGA" FLOAT, \n\t"FG%" FLOAT, \n\t"3P" FLOAT, \n\t"3PA" FLOAT, \n\t"3P%" FLOAT, \n\t"2P" FLOAT, \n\t"2PA" FLOAT, \n\t"2P%" FLOAT, \n\t"eFG%" FLOAT, \n\t"FT" FLOAT, \n\t"FTA" FLOAT, \n\t"FT%" FLOAT, \n\t"ORB" FLOAT, \n\t"DRB" FLOAT, \n\t"TRB" FLOAT, \n\t"AST" FLOAT, \n\t"STL" FLOAT, \n\t"BLK" FLOAT, \n\t"TOV" FLOAT, \n\t"PF" FLOAT, \n\t"PTS" FLOAT\n)'), ('table', 'Per100_2023-24', 'Per100_2023-24', 60, 'CREATE TABLE "Per100_2023-24" (\n\t"Player" TEXT, \n\t"Pos" TEXT, \n\t"Age" BIGINT, \n\t"Tm" TEXT, \n\t"G" BIGINT, \n\t"GS" BIGINT, \n\t"MP" BIGINT, \n\t"FG" FLOAT, \n\t"FGA" FLOAT, \n\t"FG%" FLOAT, \n\t"3P" FLOAT, \n\t"3PA" FLOAT, \n\t"3P%" FLOAT, \n\t"2P" FLOAT, \n\t"2PA" FLOAT, \n\t"2P%" FLOAT, \n\t"FT" FLOAT, \n\t"FTA" FLOAT, \n\t"FT%" FLOAT, \n\t"ORB" FLOAT, \n\t"DRB" FLOAT, \n\t"TRB" FLOAT, \n\t"AST" FLOAT, \n\t"STL" FLOAT, \n\t"BLK" FLOAT, \n\t"TOV" FLOAT, \n\t"PF" FLOAT, \n\t"PTS" FLOAT, \n\t"ORtg" FLOAT, \n\t"DRtg" BIGINT\n)')]

[('table', 'Season_Stats_2022-23', 'Season_Stats_2022-23', 24, 'CREATE TABLE "Season_Stats_2022-23" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"PLAYER_AGE" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'Season_Stats_1994-95', 'Season_Stats_1994-95', 45, 'CREATE TABLE "Season_Stats_1994-95" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"PLAYER_AGE" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'Season_Stats_2023-24', 'Season_Stats_2023-24', 2, 'CREATE TABLE "Season_Stats_2023-24" (\n\t"ID" BIGINT, \n\t"Name" TEXT, \n\t"Age" FLOAT, \n\t"MIN" FLOAT, \n\t"GP" BIGINT, \n\t"PTS" BIGINT, \n\t"REB" BIGINT, \n\t"AST" BIGINT, \n\t"STL" BIGINT, \n\t"BLK" BIGINT, \n\t"TOV" BIGINT, \n\t"PF" BIGINT, \n\t"FG_PCT" FLOAT, \n\t"FG3_PCT" FLOAT, \n\t"FT_PCT" FLOAT, \n\t"PPG" FLOAT, \n\t"RPG" FLOAT, \n\t"APG" FLOAT, \n\t"SPG" FLOAT, \n\t"BPG" FLOAT, \n\t"ToPG" FLOAT, \n\t"PFPG" FLOAT, \n\t"MPG" FLOAT\n)'), ('table', 'sqlite:///../../Ballbase.db', 'sqlite:///../../Ballbase.db', 55, 'CREATE TABLE "sqlite:///../../Ballbase.db" (\n\t"index" BIGINT, \n\t"Player" TEXT, \n\t"Pos" TEXT, \n\t"Age" BIGINT, \n\t"Tm" TEXT, \n\t"G" BIGINT, \n\t"GS" BIGINT, \n\t"MP" BIGINT, \n\t"FG" FLOAT, \n\t"FGA" FLOAT, \n\t"FG%" FLOAT, \n\t"3P" FLOAT, \n\t"3PA" FLOAT, \n\t"3P%" FLOAT, \n\t"2P" FLOAT, \n\t"2PA" FLOAT, \n\t"2P%" FLOAT, \n\t"FT" FLOAT, \n\t"FTA" FLOAT, \n\t"FT%" FLOAT, \n\t"ORB" FLOAT, \n\t"DRB" FLOAT, \n\t"TRB" FLOAT, \n\t"AST" FLOAT, \n\t"STL" FLOAT, \n\t"BLK" FLOAT, \n\t"TOV" FLOAT, \n\t"PF" FLOAT, \n\t"PTS" FLOAT, \n\t"ORtg" BIGINT, \n\t"DRtg" BIGINT\n)')]

## Load Table

In [3]:
db_path="sqlite:///../..//Ballbase.db" 
table_name= "Season_Stats_2023-24" 
engine=sqlalchemy.create_engine(db_path) 
df_from_db=pd.read_sql(table_name, con=engine)
df_from_db.sort_values('PTS', ascending=False)

,ID,Name,Age,MIN,GP,PTS,REB,AST,STL,BLK,TOV,PF,FG_PCT,FG3_PCT,FT_PCT,PPG,RPG,APG,SPG,BPG,ToPG,PFPG,MPG
219,1629029,Luka Doncic,25.0,2624.0,70,2370,647,686,99,38,282,149,0.487,0.382,0.786,33.9,9.2,9.8,1.4,0.5,4.0,2.1,37.5
192,1628983,Shai Gilgeous-Alexander,25.0,2553.0,75,2254,415,465,150,67,162,184,0.535,0.353,0.874,30.1,5.5,6.2,2.0,0.9,2.2,2.5,34.0
73,203507,Giannis Antetokounmpo,29.0,2567.0,73,2222,841,476,87,79,250,210,0.611,0.274,0.657,30.4,11.5,6.5,1.2,1.1,3.4,2.9,35.2
187,1628973,Jalen Brunson,27.0,2726.0,77,2212,278,519,70,13,186,144,0.479,0.401,0.847,28.7,3.6,6.7,0.9,0.2,2.4,1.9,35.4
96,203999,Nikola Jokic,29.0,2737.0,79,2085,976,708,108,68,237,194,0.583,0.359,0.817,26.4,12.4,9.0,1.4,0.9,3.0,2.5,34.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1631199,Ron Harper Jr.,24.0,4.0,1,0,0,1,0,0,0,2,0.000,0.000,0.000,0.0,0.0,1.0,0.0,0.0,0.0,2.0,4.0
456,1631219,John Butler Jr.,0.0,0.0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,201937,Ricky Rubio,0.0,0.0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
172,1628427,Vlatko Cancar,0.0,0.0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530,1641936,Miles Norris,0.0,0.0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Split Table

In [4]:
# Total Stats Table 
totals = df_from_db.loc[:, 'Name':'FT_PCT'].sort_values('PTS', ascending=False) 

# Per Game Stats Table  
avgs = df_from_db.loc[:,['Name', 'Age', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'ToPG',	'PFPG', 'MPG', 'FG_PCT', 'FG3_PCT',	'FT_PCT']].sort_values('PPG', ascending=False)  

totals 
avgs 

contents = [totals, avgs]

## Convert to HTML

In [5]:
# Create HTML table version 
for i in range(len(contents)):
    contents[i] = contents[i].to_html(table_id="table", classes = "table table-hover table-stripped table-bordered table-dark", index=False)

# Create page content 
for i in range(len(contents)):
    contents[i] = f"""
    {{%extends 'TableBase.html'%}}

    {{% block table %}}
    {contents[i]}
    {{% endblock %}}
"""

## Export to Page

In [6]:
def write_to_file(path, content): 
    file = open(path, "w", encoding="utf-8") 
    file.write(content) 
    file.close 


file_names=["Totals.html", "PerGame.html"] 

for i in range(len(contents)): 
    path = f"../templates/Tables/{file_names[i]}" 
    write_to_file(path, contents[i])

FileNotFoundError: [Errno 2] No such file or directory: '../templates/Tables/Totals.html'